import 'package:search_script/models/game_info.dart';

import 'models/league.dart';
import 'models/match.dart';
import 'models/summoner.dart';

class Utils {
  // Json variables
  static Summoner summonerData;
  static List<League> leagueData;
  static List<Game> listMatches;
  static GameInfo gameInfo;

  // Players to fetch
  static List<String> playersTofetch1 = [
    'CheckMeOutImDone',
    'xpegb',
    'Jïhyo',
    'Arveel xo',
    'Akse69',
    'StrawHat Toplane',
    'JeanLucSkywalker',
    'Yõda',
    'Vaska',
    'thats Mr to you',
    'Frised',
    'Wuhu Airline fly',
    'Wenser',
    'ima simp for you',
    'SchlitzenSchlunz',
    'HimNOVAliente',
    'Master Yinter',
    'YikesKEKW',
    'Synthoros',
    'BloodyRize',
    'Yasuoismabae',
    'The Alysian',
    'PINEITES',
    'oliijd',
    'rafik4kd',
    'Gryphios',
    'AngelWolf92',
    'SyŁow',
    'TrIb3Z',
    'V7LGxSilva',
    'Im Xerxes',
    'GKUSHGNJHZ',
    'The Lost Prince',
    '1000minus',
    'mojoyoyo1337',
    'TomMowfo',
    'IceCreamIsGood',
    'Roconhofe',
    'TS Rylai Reid',
    'Getrank',
    'Naelika',
    'MicklKjW',
    'JukeLikeScuttle',
    'Zentive',
    'WATareyoudin',
    'GO suck AsshoIe',
    'Zunk',
    'CarkOo',
    'DWG Inflection',
    'kimber light',
    'victor6035',
    'Pløp',
    'Danσ',
    'SilverProtox',
    'SD Capone',
    'Signnik',
    'Despair wait',
    'wukonginlove',
    'Sacha8611',
    'Jerych',
    'Starkrow',
    'Mubs5',
    'ChaIIanggerRiven',
    'KuramaBiyuu',
    'porelcuIonopls',
    'Joshuashr',
    'Dommkiusv2',
    'n00bi teytey',
    '4 5',
    'ropei',
    'PH CaptainCalle',
    'Shén Bot',
    'Infinity Rage',
    'GeneralMerten',
    'TheMuKmaster',
    'PrincessaLeya',
    'Aziuhn',
    'ELMIRE',
    'thelanxster',
    'BardoHeftSwek',
    'Master Rush D4',
    'BigBlossBlamy',
    'Naylune',
    'M0GAMB0',
    'La Nueva Leyenda',
    'Radian007',
    'ˇº ﬂ ÆˉßˉÆ ﬁ ªˆ',
    'Hendı',
    'Verde Branco',
    'ONETWOGO',
    'Aμthenticity',
    'GermaaaN',
    'WladiS',
    'lRaid Bossl',
    'Sion April',
    'TheKilon',
    'kUiOSilvester',
    'PaRaDogi',
    'BrAzZerGameR',
    'Kinshi Samurai',
    'Allivan71',
    'peterparker2222',
    'Centaurownz',
    'XleBleh',
    'MrClunter',
    'Aisama',
    'Adrënaline',
    'Advitil',
    'le chef nutella',
    'Sailor MarsUwU',
    'Worry',
    'Emmosicko',
    'KarlosPop',
    'Gabiluss',
    'NoMasCuentos',
    'Lai Le Lao DI',
    'KuwT',
    'a201',
    'BrokenFast',
    'Tompachou',
    'Hoolly',
    'Nuclear Ziggs',
    'ChakalDelNepal',
    'Ratbake',
    'JesusDied',
    'Gohan Blanco',
    'MFRZ',
    'CS Goblin',
    'mqris',
    'Hauber',
    'eccogg',
    'HillbillyDemon',
    'Isla Delice',
    'DragonWarrior',
    'jk0q a New Dad',
    'TRN Scaldabagno',
    'VoOTOoV',
    'M4kS4ï',
    'SptZ Shinoa',
    'Mokutonhijutsu',
    'sinidex',
    'VeoSigmao',
    'FerPiggy',
    'Figureante',
    'CharLee Siin',
    'Square Sausage',
    'IYannickz',
    'mem420',
    'PiPPo23',
    'JT Vennox',
    'T1mmy der Hund',
    'Only 4 bullets',
    'Cristina96',
    'DarkAngelXxXcj',
    'mininekos',
    'BratProtato',
    'Dálriáda',
    'GeniusHK',
    'Score 87',
    'CTRlife',
    'OverTheEdge',
    'Janovy',
    'Darkiem974 V2',
    'charlomagne',
    'nokinhaz',
    'SeekDWay',
    'NukeSmoker98',
    'ilovenutellone',
    'tiziocaietto',
    'SuperLuigi10',
    'xwanted',
    'Lilliwyt',
    'Tomi Kadachi',
    'SassiLord',
    'Quartocryingwolf',
    'DNA Corldplay',
    'Kâsanai',
    'Chrioyles',
    'JuŹ',
    'kkimo',
    'Sabiuiulilou',
    'APU MadLife',
    'APU Endboss',
    'APU BigBeerBelly',
    'APU Dancer',
    'free5K',
    'CatchySenpai',
    '335Diesel',
    'OverDove',
    'Crying Sett',
    'Yasuo A',
    'Taxmann',
    'Tetrahydrofolate',
    'HátEzAShaco',
    'Anníé',
    'Hengeveld',
    '385idéal',
    'SyzeNNN',
    'Høøk',
    'Darkaddiction',
    'Farengatez',
    'TevoX'
  ];
  static List<String> playersTofetch = [
    'Delicious Mango',
    'Intosaurus Glock',
    'where is my jglr',
    'TerribleMeme1',
    'malte13052002',
    'Vel Koz Balayage',
    'rayenflo',
    'Ojoloco',
    'Phreakadelle',
    'böseß',
    'im busch',
    'Lil Flame Queen',
    'xHarkle',
    'CrotoQQ',
    'Kitaos',
    'eaerg',
    'MihoYo Sucks',
    'Life as a Tree',
    'MiniKnubb',
    '3Sammy3',
    'Kakebake',
    'Tarcheta',
    'ooops headshot',
    'Trèox',
    'FoxFiun',
    'YouPrnCEO',
    'HideOnKush420ms',
    'HerpyMcDikDurp',
    'Rechtsklìcker',
    'ameer005',
    'GFBBuddah',
    'trippy0',
    'The Surgeon Of D',
    'RoxoKam',
    'Adolf Naturgy',
    'EnokIsAwesome',
    'Styxiee',
    'RLaFinestra',
    'NijntjeKonijntje',
    'Alpargato',
    'Furfu',
    'SOBGE',
    'Daddy came home',
    'Lowti6',
    'SiedlaZ',
    'Savli',
    'DN7500',
    'Snoop Dogue',
    'TDKnight',
    'Dean Thomas',
    'suné11',
    'White Lilium',
    'kurd72',
    'JobWp',
    'HU TAO WHY',
    'Murky Okami',
    'Piloot',
    'JORDSU',
    'Ramk1ng',
    'itsdullo98',
    'MrDullo6',
    'David200001',
    'EnderRex501',
    'Λrtic',
    'Kurgix',
    'topgap6969',
    'Yumii',
    'bycy',
    'DashyLilTiltWall',
    'Pivek',
    'OG Little',
    'Eleftheria',
    'kronaa',
    'OverFireFlash',
    'Alancienne',
    'TooMuchSkill4You',
    'SatHellfire',
    'het is kees',
    'Gympie5',
    'Synt',
    'Vity86',
    'Nguyen',
    'B1ueflamingo',
    'zHarakiri',
    'Ristet Brød',
    'Smeltet',
    'Smør',
    'D Z 12',
    'za7ef187',
    'Kingsthor',
    'Sherran',
    'Gandera',
    'Moumen',
    'R4ndom Grimmlock',
    'Aschente01',
    'Antonio7797',
    'Miri00',
    'El Joguin',
    'Myxto',
    'Kuratep',
    'Ljfe',
    'Limburguer',
    'Luminon',
    'INTfeed Taliyah',
    'OTP Bronze Btw',
    'ImXarnox',
    'KristenBooo',
    'Dedrack',
    'JE SUIS PIKACHU',
    'FauxTom',
    'TrøisNightCrew',
    'Hornpep',
    '69WeedWizard420',
    'Audamus',
    'GAGABABA321',
    'SkyGames2001',
    'RacheI',
    'MäkkaPäkka',
    'Razzamataz',
    'larry thinman',
    'JaffarTheJamJar',
    'Kral Leblanc',
    'BeaveR b0y',
    'oskar2k',
    'sperify',
    'Xanimus',
    'KERR0S',
    '2 AXE 1 GUY',
    'xHighper',
    'elo gatekeeperr',
    'Azolie',
    'chronasoul',
    'tsie',
    'Kuub Stront',
    'Meloooooo7',
    'OM Mítroglou',
    'Grád',
    'BigIronSkunk',
    'vkzbc',
    'Qp3rd4d3t3mp0',
    'UABoostedBonobo',
    'RSQ Vice',
    'SG Backlight',
    'ÁMP',
    'Sukyaki',
    'BaneameLasBolas',
    'Flash4thShºt',
    'HunterJasonn2',
    'subsessor',
    'Soulreaver66',
    'Supe2',
    'Not Very Helpful',
    'Chealsea AGK',
    'Deadlyhush',
    'Cancrelas',
    'Kunivα',
    'Vivi Ornitier IX',
    'Paviel Rochnyak',
    'itachi c1',
    'LilGreyCat',
    'TrevOrGoTTa',
    'KEKSPARROW',
    'Gilbert369',
    'romidav',
    'BatuBang',
    'ChallengerInMind',
    'Matuszewski',
    'Az4thoth',
    'Sebo da Häftige',
    'Xico Elias',
    'Chadosplayer',
    'TheExiled32',
    'iK4liStA',
    'Gattο',
    'ItsSteasyMofacka',
    'MissMegs',
    'DAOBHER',
    'TheAwesomeGinger',
    'xBelgiumXhunter',
    'Xivan',
    'RPC PETRICHOR',
    'Crush on Yeonjun',
    'DiIdo Bagins',
    'toph º',
    'EGirlMain02',
    'xXSKILLMELONXx',
    'Kerrah',
    'GlNGER BEER',
    'Franciscus',
    'JhingIe beIIs',
    'Mochou4',
    'xCoreox',
    'IEEEIeeee',
    'DarkShadowoo7',
    'Snıpı',
    'Daaviid99',
    'Liposussion',
    'Chlacvuc',
    'Cratobie',
    'M de Marc',
    'Raccoon Dog',
    'quantµm',
    'MXZENON',
    'LLSTYLZED',
    'SDFonzie',
    'AxelXyfer',
    'The BIind Munk',
    'JFF Clean',
    'Imßad',
    'kikishoo',
    'CusCus23',
    'Den mandige Elg',
    'Zouuuk',
    'Lé baguétté',
    'Blakondas',
    'Akse69',
    'Rimtega420',
    'ganso89123',
    'Etra',
    'Lou Gabian',
    'Aldmeria',
    'CookieStrada',
    'hr0dWulf',
    'LeoftwXD',
    'deerbaumxD1212',
    'CiccioPe26',
    'Zeeko69',
    'ZackFair100700',
    'CheckMeOutImDone',
    'xpegb',
    'Jïhyo',
    'Arveel xo',
    'StrawHat Toplane',
    'JeanLucSkywalker',
    'Yõda',
    'Vaska'
  ];
}
